name: Build MediaApp APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: Java 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Gradle Wrapper Ekle
      run: gradle wrapper --gradle-version 8.5

    - name: İzinleri Ayarla
      run: chmod +x gradlew

    - name: APK Derle (Debug)
      run: ./gradlew assembleDebug

    - name: APK Dosyasını Yükle
      uses: actions/upload-artifact@v4
      with:
        name: MediaApp-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        
