name: Build or Test MediaApp

on:
  workflow_dispatch:
    inputs:
      build_apk:
        description: 'APK dosyası üretilsin mi?'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: Java 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Tam Uyumlu Gradle Kurulumu
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    # Sadece kodları ve derlemeyi test eder (Hızlı mod)
    - name: Kod Kontrolü ve Derleme Testi
      if: ${{ !inputs.build_apk }}
      run: gradle compileDebugSources

    # Sadece kutucuk işaretlendiyse tam APK derler
    - name: APK Derle (Debug)
      if: ${{ inputs.build_apk }}
      run: gradle assembleDebug

    # Sadece APK derlendiyse dosyayı yükler
    - name: APK Dosyasını Yükle
      if: ${{ inputs.build_apk }}
      uses: actions/upload-artifact@v4
      with:
        name: MediaApp-APK
        path: app/build/outputs/apk/debug/app-debug.apk
