name: Build MediaApp APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: Java 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Tam Uyumlu Gradle Kurulumu
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    - name: APK Derle (Debug)
      run: gradle assembleDebug

    - name: APK Dosyasını Yükle
      uses: actions/upload-artifact@v4
      with:
        name: MediaApp-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        
